baseURL = "https://sendailogic.com/"
title = "Sendai Logic - 仙台ロジック"
theme = "fuji"
hasCJKLanguage = true
enableEmoji = true
enableRobotsTXT = true
disableKinds = ["RSS", "taxonomyTerm"]

## Change this two to switch between different language
## Now support: en, zh-hans, zh-hant, ja, nl
defaultContentLanguage = "en"
languageCode = "en"

summaryLength = 100 # Custom cummary length, add <!--more--> in post file to custom split point
paginate = 1

[permalinks]
  post = "/:filename/" # Custom post links, e.g. "/:year/:month/:title/"

[params]
  author = "Sendai Logic" # You can also set author in post front matter individually
  # subtitle is directly coded to the head.html partial
  # subTitle = "Mathematical Institute, Graduate School of Science, Tohoku University"

  # Open Graph & Twitter Card variables
  # You can also set description and images in post front matter individually
  description = "A minimal hugo theme powered by Primer CSS."
  images = ["img/og.png"] # This will use the image called og.png in static/img folder

  # Posts shown in homepage
  mainSections = ["post"]

  # Bangumi image chart id
  # bgmImageChart = "000000"

  # Show scroll to top button
  scrollTop = true

  # License
  noLicense = true
  # license = "Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License (CC BY-NC-SA 4.0)"
  # licenseLink = "http://creativecommons.org/licenses/by-nc-sa/4.0/"

  # Comments
  # utterances, see: https://utteranc.es/
  # utterancesRepo = "[ENTER REPO HERE]"
  # utterancesIssueTerm = "pathname"
  # utterancesTheme = "github-light"

  # Custom lazyload placeholder
  # 16:9
  cdnLazyPlaceholder = "https://cdn.jsdelivr.net/gh/amzrk2/poal-jsdelivr@1.1.0/lazyload/dsrca_loading_480x270.svg"
  # 32:9
  cdnLazyPlaceholderRow = "https://cdn.jsdelivr.net/gh/amzrk2/poal-jsdelivr@1.1.0/lazyload/dsrca_loading_960x270.svg"
  # 8:9
  cdnLazyPlaceholderCol = "https://cdn.jsdelivr.net/gh/amzrk2/poal-jsdelivr@1.1.0/lazyload/dsrca_loading_480x540.svg"

  # enable this to fetch css & js from jsDelivr CDN
  useCDN = true

[markup]
  [markup.highlight]
    style = "monokailight"

  [markup.tableOfContents]
    startLevel = 2
    endLevel = 2

[taxonomies]
  tag = "tags"

[menu]
#  [[menu.nav]]
#    name = "Home"
#    url = "/"
#    weight = 1
  [[menu.nav]]
    name = "Kazuyuki Tanaka's CV"
    url = "/tanaka/"
    weight = 2
  [[menu.nav]]
    name = "Publications"
    url = "/publications/"
    weight = 3
  [[menu.nav]]
    name = "Books"
    url = "/books/"
    weight = 4
  [[menu.nav]]
    name = "CTFM"
    url = "/ctfm/"
    weight = 5
  [[menu.nav]]
    name = "SLS"
    url = "/sls/"
    weight = 6
#  [[menu.nav]]
#    name = "Members"
#    url = "/members/"
#    weight = 7
#  [[menu.nav]]
#    name = "Archives"
#    url = "/archives/"
#    weight = 8
#  [[menu.nav]]
#    name = "About"
#    url = "/about/"
#    weight = 9
